### ISSUE TITLE
Invalid Tag values in OCR

### ISSUE THREAD

**Issue by supercmmetry** [smoke-trees/model-zoo#9]
The **results.json** file in OCR has **"Tags": [["Optical Character Recognition"],["OCR"]]** which does not conform to the given format.
It should be **"Tags": ["Optical Character Recognition","OCR"].**

**Comment by lordtt13** [comment]
@Mastermind0100 please move all models which haven't completed all checks to branch, create PR and link this issue

**Comment by lordtt13** [comment]
Error resolved
